[project]
name = "weather-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "mcp-server[http]>=0.1.4",
    "mcp[cli]>=1.9.3",
    "starlette>=0.47.0",
    "uvicorn>=0.34.3",
]
